version: '3.8'

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://nghianh:6d0yfrpx2tbw7hmz@137.184.250.68:27017/sem?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
